services:
  my_mariadb:
    container_name: my_mariadb_container
    build: ./requirements/mariadb
    restart: always
    environment:
      DB_NAME: wordpress_db
      DB_PASSWORD: 120701A
      DB_USER: wordpress_admin
      DB_ROOT_PASS: test90
    networks:
      - unix
  my_wordpress:
    container_name: my_wordpress_container
    build: ./requirements/wordpress
    volumes:
      - wordpressV:/var/www/html
    depends_on:
      - my_mariadb
    environment:
      WORDPRESS_DB_HOST: my_mariadb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_admin
      WORDPRESS_DB_PASSWORD: 120701A
    links:
      - my_mariadb
    networks:
      - unix
    restart: always
    # hostname: wordpress1
  my_nginx:
    container_name: my_nginx_container
    build: ./requirements/nginx
    ports:
      - "1122:80"
    depends_on:
      - my_wordpress
    volumes:
     - ./requirements/nginx/conf.d/:/etc/nginx/conf.d
     - ./requirements/nginx/logs:/var/log/nginx
     - wordpressV:/var/www/html
    links:
     - my_wordpress
    networks:
      - unix
    # hostname: nginx1
volumes:
  wordpressV:
  sockets:
networks:
  unix:
    driver: bridge
